version: "3.9"

services:
  demo-app:
    image: mijumall/demo-app
    deploy:
      replicas: 1
    networks:
      - app-overlay-net
    command: deno run --allow-env --allow-read --allow-net /demo-app-build/index.js


  curl:
    image: curlimages/curl
    deploy:
      mode: global
    networks:
      - app-overlay-net
    command: sleep 1000000


networks:
  app-overlay-net:
    driver: overlay
